
CREATE DATABASE BiblioWebDb;
GO

USE BiblioWebDb;
GO

CREATE TABLE TbUsuario(
Id_Usuario INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Correo NVARCHAR(30) NOT NULL,
Contraseña NVARCHAR(30) NOT NULL
);
GO

CREATE TABLE TbCliente(
Id_Cliente INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Nombre NVARCHAR(30) NOT NULL,
ApellidoPat NVARCHAR(30) NOT NULL,
ApellidoMat NVARCHAR(30) NOT NULL,
Colonia NVARCHAR(30) NULL,
Calle NVARCHAR(30) NULL,
Numero INT NULL,
Id_Usuario INT NOT NULL,

CONSTRAINT fk_Usuario FOREIGN KEY (Id_Usuario) REFERENCES TbUsuario(Id_Usuario)
);
GO

CREATE TABLE TbLibro(
Id_Libro INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Titulo NVARCHAR(50) NOT NULL,
Autor NVARCHAR(50) NOT NULL,
Genero NVARCHAR(50) NOT NULL,
Descripcion NVARCHAR(MAX) NOT NULL,
Cantidad NVARCHAR(3) NOT NULL,
Precio NVARCHAR(20) NOT NULL,
Ruta NVARCHAR(50) NOT NULL
);
GO

CREATE TABLE TbPedido(
Id_Pedido INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Id_Libro INT NOT NULL,
Id_Usuario INT NOT NULL,
Visibilidad BIT NOT NULL,
CONSTRAINT fk_Libro_Pedido FOREIGN KEY (Id_Libro) REFERENCES TbLibro(Id_Libro),
CONSTRAINT fk_Usuario_Pedido FOREIGN KEY (Id_Usuario) REFERENCES TbUsuario(Id_Usuario)

);
GO

CREATE TABLE TbVentas(
Id_Ventas INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Fecha DATETIME NOT NULL,
Id_Pedido INT NOT NULL,

CONSTRAINT fk_Pedido FOREIGN KEY (Id_Pedido) REFERENCES TbPedido(Id_Pedido)
);
GO

DELETE FROM TbLibro
WHERE Id_Libro = '1'

DELETE FROM TbPedido
WHERE Id_Pedido = '2'

DELETE FROM TbVentas
WHERE Id_Ventas = '2'


SELECT * FROM TbPedido
SELECT * FROM TbUsuario
SELECT * FROM TbCliente
SELECT * FROM TbLibro
SELECT * FROM TbVentas